apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: heketi
  name: consulvault-pvc1
  namespace: security
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
